<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Run Python Script</title>
</head>
<body>
    <h1>Run Python Script from Webpage</h1>
    <button onclick="runScript()">Run Script</button>

    <script>
        function runScript() {
            fetch('/run_script')
                .then(response => response.text())
                .then(data => alert(data));
        }
    </script>
</body>
</html>
